# Generated by Django 3.2.2 on 2021-09-20 11:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
