# Generated by Django 3.2.2 on 2021-08-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210730_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='sec_token',
        ),
    ]
