# Generated by Django 3.2.2 on 2021-07-30 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200)),
                ('avatar', imagekit.models.fields.ProcessedImageField(null=True, upload_to='')),
                ('cover', imagekit.models.fields.ProcessedImageField(null=True, upload_to='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_celebrity', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('id', 'user')},
            },
        ),
    ]
