# Generated by Django 3.2.2 on 2021-08-10 10:01

from django.db import migrations
import imagekit.models.fields
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_token_user_sec_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(max_length=1000, null=True, upload_to=user.utils.upload_to_user_directory),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(max_length=1000, null=True, upload_to=user.utils.upload_to_user_directory),
        ),
    ]
